api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "location-routing-by-properties"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.fulfillment-groups.location-rankings.generate.run"
  input_query = "src/cart_fulfillment_groups_location_rankings_generate_run.graphql"
  export = "cart_fulfillment_groups_location_rankings_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-wasip1 --release"
  path = "target/wasm32-wasip1/release/location-routing-by-properties.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
